### ISSUE TITLE
Empty list of devices on Windows build

### ISSUE THREAD

**Issue by YoungReckless4** [sctg-development/sctgdesk-server#15]
**Describe the bug**
Device list is empty after configuring and logging into server on client.

**Describe the environment**
Latest sctgdesk-server windows release on WS 2019.
Default settings on deploy with a new created user using pm2.

**How to Reproduce the bug**
Just run sctgdesk server on Windows OS with default settings, configure client and check Devices on web panel.

**Notes**
Thank You for Your work!

**Comment by aeltorio** [comment]
Hi @YoungReckless4 ,
First thank you for your message.  
I do not have access to WS2019 but on my WS2022 standard I cannot reproduce it, could you run hbbs.exe with the `RUST_LOG` environment variable set to `debug` and verify that your remote client register in the server.  
Also you can check the `peer` table on `db_v2.sqlite`

**Comment by YoungReckless4** [comment]
@aeltorio 
It's very strange, but I can't run parameters in hbbs, including it doesn't take settings from the .env file.
I don't understand how to solve this yet, but I don't think it's related to your development.

I found some lines in the hbbs error log, do they affect the work?

``thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\git\checkouts\sctgdesk-api-server-f34deca99ea6f238\bc33339\libs\state\src\database.rs:117:14:``
``called `Result::unwrap()` on an `Err` value: Database(SqliteError { code: 8, message: "attempt to write a readonly database" })``
``note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace``
``thread 'main' panicked at src/main.rs:98:19:``
``called `Result::unwrap()` on an `Err` value: Any { .. }``

**Comment by YoungReckless4** [comment]
I understand, these records appear if there are no rights.
In this case, I will figure out why something is not working correctly for me.
Thank You.

**Comment by aeltorio** [comment]
@YoungReckless4 ,

It looks like the issue is related to database access permissions. The error message indicates that the server is attempting to write to a read-only database, which is causing the panic:

```
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\git\checkouts\sctgdesk-api-server-f34deca99ea6f238\bc33339\libs\state\src\database.rs:117:14:
called `Result::unwrap()` on an `Err` value: Database(SqliteError { code: 8, message: "attempt to write a readonly database" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:98:19:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

The problem seems to stem from the server's inability to write to the database. This prevents peers from appearing because the `heartbeat` call, which updates the database, fails. The `heartbeat` endpoint is responsible for the green status indicator next to the computer view in Rustdesk. Each Rustdesk client continuously hits this endpoint to signal that it is alive.

To resolve this, ensure that the database file has the correct write permissions. You might need to adjust the file permissions or the configuration of your database to allow write access.

**Comment by aeltorio** [comment]
@YoungReckless4

Alternatively, have you tried using Docker with WSL on Windows server?  
It offers low CPU overhead. Additionally, if you're not part of a large company (250 employees or $10M USD in revenue), Docker Desktop is free to use.

**Comment by eltorio** [comment]
Closed because there is no update for more than one month
